name: Label issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label to the issue
        run: |
          gh issue edit "${{ github.event.issue.number }}" --add-label "Todo"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
