name: Manage Issue Labels
on:
  issues:
    types:
      - opened
      - reopened
      - edited
      - labeled
      - unlabeled

jobs:
  manage_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set up GitHub CLI
        run: |
          if ! command -v gh &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y gh
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Add or Update Labels
        run: |
          # Fetch the current issue labels
          current_labels=$(gh issue view "${{ github.event.issue.number }}" --json labels --jq '.labels[].name')

          # Check if the issue already has one of the project labels
          if echo "$current_labels" | grep -q -E "Todo|In Progress|Done"; then
            echo "Removing existing project labels."
            # Remove existing labels
            gh issue edit "${{ github.event.issue.number }}" --remove-label Todo,In\ Progress,Done
          fi

          # Add the appropriate label (default to Todo if no other condition applies)
          gh issue edit "${{ github.event.issue.number }}" --add-label "Todo"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
